/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_HZpKbsrUz",
    //"aws_identity_pools_id": 'ca-central-1:54ed8cde-e1f4-4ee2-a58e-dc70564f6747',
    "aws_user_pools_web_client_id": "3o5k42eddai0dacvv51ejjj5hb",
    "federationTarget": "COGNITO_USER_POOLS",
    "Auth": {
        "region": "ca-central-1",
        "userPoolId": "ca-central-1_HZpKbsrUz",
        "userPoolWebClientId": "3o5k42eddai0dacvv51ejjj5hb",
        //"identityPoolId": "ca-central-1:54ed8cde-e1f4-4ee2-a58e-dc70564f6747",
        "mandatorySignIn": false,
        "authenticationFlowType": "USER_PASSWORD_AUTH"
    }
};


export default awsmobile;
